# Generated by Django 5.0.2 on 2024-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termEN', models.CharField(max_length=100)),
                ('termSP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guías',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=100)),
                ('categoría', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caract', models.CharField(max_length=100)),
            ],
        ),
    ]
