# Generated by Django 5.0.2 on 2024-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Acrónimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrónimo', models.CharField(max_length=100)),
                ('definición', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Glosario',
            new_name='Glosarios',
        ),
        migrations.DeleteModel(
            name='Consultas',
        ),
    ]
