# Generated by Django 5.0.2 on 2024-03-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_acerca_acrónimos_rename_glosario_glosarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acerca',
            options={'verbose_name': 'Acerca', 'verbose_name_plural': 'Acerca'},
        ),
        migrations.AlterModelOptions(
            name='acrónimos',
            options={'ordering': ['acrónimo'], 'verbose_name': 'Acrónimos', 'verbose_name_plural': 'Acrónimos'},
        ),
        migrations.AlterModelOptions(
            name='glosarios',
            options={'ordering': ['termSP'], 'verbose_name': 'Glosarios', 'verbose_name_plural': 'Glosarios'},
        ),
        migrations.AlterModelOptions(
            name='guías',
            options={'verbose_name': 'Guías', 'verbose_name_plural': 'Guías'},
        ),
        migrations.AlterModelOptions(
            name='herramientas',
            options={'verbose_name': 'Herramientas', 'verbose_name_plural': 'Herramientas'},
        ),
    ]
