# Generated by Django 5.0.2 on 2024-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_acrónimos_definición'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='enlace',
            field=models.CharField(default='Valor por defecto', max_length=100),
        ),
    ]
