# Generated by Django 5.0.2 on 2024-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_herramientas_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='caract',
            field=models.CharField(max_length=500),
        ),
    ]
