# Generated by Django 5.0.2 on 2024-03-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_herramientas_caract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glosarios',
            options={'verbose_name': 'Glosarios', 'verbose_name_plural': 'Glosarios'},
        ),
        migrations.AlterModelOptions(
            name='guías',
            options={'ordering': ['categoría'], 'verbose_name': 'Guías', 'verbose_name_plural': 'Guías'},
        ),
        migrations.RenameField(
            model_name='glosarios',
            old_name='termEN',
            new_name='Término_EN',
        ),
        migrations.RenameField(
            model_name='glosarios',
            old_name='termSP',
            new_name='Término_SP',
        ),
    ]
