# Generated by Django 5.0.2 on 2024-03-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramientas',
            old_name='caract',
            new_name='Descripción',
        ),
        migrations.RenameField(
            model_name='herramientas',
            old_name='enlace',
            new_name='Enlace',
        ),
        migrations.RenameField(
            model_name='herramientas',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
